sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: qrHyXYJbH3C5Vv2imXDNVCnFvGp1jluyz4HoXFVMJapvDVArFylWC7uAGIbLHtV6euPzg7ccaP9x0qRSfm0hiRq0uC+gmDIspSAcsU4OFyw05VufOEO/9Li0al4IxshY14ohmR+1uCIPACn2s7GtyKJlUXxprsP4WqDFuCHYdAAkLfgWb/psko6oQobF0sqcqLbfezdDQ+kFTz2QY/agRQfeyKIwgP95Pl3tqhDoA8RGW5UhMxtoDSWYOXj5XIiHvtouddYmJnrMbC7pN0pn2KBNMReX6gjC3XIrdOxzG/RdAaMKMZ2bwyWNre1mgXwXsa7ZJ8im4h3FUmkMNX3tdidbFpUFwsYdU0+TUwI+tQgOoIMYVhGydYLf/HN1ZSZZWeuHVJIcemTUzV9+041KOrfsNS+b3XukPeY4KwlVGOcQEqBa+TMXo3V5jNX1BH5jpIC93EQdu/H5vuNrSVs3Bh3sQJMd9ruda9o4KSBtYIJE0DZBeooWOXtkHVcpWxIc6dh3G1wEq0oyX4loVAKeu7xpDD0CSQAS+EJK8APiWLyi6+x3wrIWPO972wrJyU+rS1gSwzo2nyN5dMk6+N4NVeq03k8myZhCpT+ve4VWvNj8e8gOIlatspwz7ddW3oqRSE5SnznI/h/RlpoKh/xHic9KSPzzFGDvyOqc+xQKUtU=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: pJI8KVA0xC8p/3ayGKzhoFjBTSrWR7ElEWz7q9t2W6HGBzNbkI/lZLJXy+L3ixn4EEP2ov11kLKlNWe7yysRjk4PQNorUCKy9CXHgKfO27sLe9ZCsCznOQ8cRbmee0hE4/xZVTKzN9BQHf9vbXGtgT+cPYnPFIzQEEdP7An8XyiKbpqnSvSCVvMI7o7HOhBh16SRvUxO23l1/4/2vDCzHYLqU67JBu8+EWpT1avXXMHJRY46ul/nMAH9gu43+5PJvNPEoN8CEQRnlk5oEI+0X+yhL01i2xO0+hQb50s6ky/bTinM+d5GRKc1mf9Q2qaZyABXLl2UhHn2QySZR4DJtA0HJ7AOUyTjxd2kUP4+skqGZDdPBrLzXU0vPniKijl28rJHeUILZ5lldHBgPyfxxZCVh3IGnAEjltncDExQ2QmI5YtY4SlwNruN++f3Ht6FpnUxoUS+kWjmM9MaR5WYvMj+yX5wHCuHLMAFVyORPSRvkaMW2yp76UfOfmJlMPC11DvUskB5mu0xAy7NQB8ek7Xnh/d8dJEeSQH6hGqzFEr/R/q9OlDD/xB0vDnyssI9geVd5Lz0rIp1M/8ldiYQHUvrooigjFZdH2sv7BGAWB1tLq6U859wxhHQ0bCXMzBpXHKgLJleRERVmn+Ln6DLXlNXhDXdDcx7Yy1BJ0cbknU=
